DROP DATABASE IF EXISTS TPCH_TEST;
CREATE DATABASE TPCH_TEST;
\c tpch_test;
CREATE TABLE REGION (
  R_REGIONKEY INTEGER NOT NULL,
  R_NAME CHAR(25) NOT NULL,
  R_COMMENT VARCHAR(152) DEFAULT NULL
);

CREATE TABLE NATION (
  N_NATIONKEY INTEGER NOT NULL,
  N_NAME CHAR(25) NOT NULL,
  N_REGIONKEY INTEGER NOT NULL,
  N_COMMENT VARCHAR(152) DEFAULT NULL
);


CREATE TABLE PART (
  P_PARTKEY INTEGER NOT NULL,
  P_NAME VARCHAR(55) NOT NULL,
  P_MFGR CHAR(25) NOT NULL,
  P_BRAND CHAR(10) NOT NULL,
  P_TYPE VARCHAR(25) NOT NULL,
  P_SIZE INTEGER NOT NULL,
  P_CONTAINER CHAR(10) NOT NULL,
  P_RETAILPRICE DECIMAL(15,2) NOT NULL,
  P_COMMENT VARCHAR(23) NOT NULL
);


CREATE TABLE SUPPLIER (
  S_SUPPKEY INTEGER NOT NULL,
  S_NAME CHAR(25) NOT NULL,
  S_ADDRESS VARCHAR(40) NOT NULL,
  S_NATIONKEY INTEGER NOT NULL,
  S_PHONE CHAR(15) NOT NULL,
  S_ACCTBAL DECIMAL(15,2) NOT NULL,
  S_COMMENT VARCHAR(101) NOT NULL
);

CREATE TABLE PARTSUPP (
  PS_PARTKEY INTEGER NOT NULL,
  PS_SUPPKEY INTEGER NOT NULL,
  PS_AVAILQTY INTEGER NOT NULL,
  PS_SUPPLYCOST DECIMAL(15,2) NOT NULL,
  PS_COMMENT VARCHAR(199) NOT NULL
);

CREATE TABLE CUSTOMER (
  C_CUSTKEY INTEGER NOT NULL,
  C_NAME VARCHAR(25) NOT NULL,
  C_ADDRESS VARCHAR(40) NOT NULL,
  C_NATIONKEY INTEGER NOT NULL,
  C_PHONE CHAR(15) NOT NULL,
  C_ACCTBAL DECIMAL(15,2) NOT NULL,
  C_MKTSEGMENT CHAR(10) NOT NULL,
  C_COMMENT VARCHAR(117) NOT NULL
);

CREATE TABLE ORDERS (
  O_ORDERKEY INTEGER NOT NULL,
  O_CUSTKEY INTEGER NOT NULL,
  O_ORDERSTATUS CHAR(1) NOT NULL,
  O_TOTALPRICE DECIMAL(15,2) NOT NULL,
  O_ORDERDATE DATE NOT NULL,
  O_ORDERPRIORITY CHAR(15) NOT NULL,
  O_CLERK CHAR(15) NOT NULL,
  O_SHIPPRIORITY INTEGER NOT NULL,
  O_COMMENT VARCHAR(79) NOT NULL
);

CREATE TABLE LINEITEM (
  L_ORDERKEY INTEGER NOT NULL,
  L_PARTKEY INTEGER NOT NULL,
  L_SUPPKEY INTEGER NOT NULL,
  L_LINENUMBER INTEGER NOT NULL,
  L_QUANTITY DECIMAL(15,2) NOT NULL,
  L_EXTENDEDPRICE DECIMAL(15,2) NOT NULL,
  L_DISCOUNT DECIMAL(15,2) NOT NULL,
  L_TAX DECIMAL(15,2) NOT NULL,
  L_RETURNFLAG CHAR(1) NOT NULL,
  L_LINESTATUS CHAR(1) NOT NULL,
  L_SHIPDATE DATE NOT NULL,
  L_COMMITDATE DATE NOT NULL,
  L_RECEIPTDATE DATE NOT NULL,
  L_SHIPINSTRUCT CHAR(25) NOT NULL,
  L_SHIPMODE CHAR(10) NOT NULL,
  L_COMMENT VARCHAR(44) NOT NULL
);

\Copy region FROM './region.tbl' DELIMITER '|';
\Copy nation FROM './nation.tbl'  DELIMITER '|';
\Copy part FROM './part.tbl'  DELIMITER '|';
\Copy supplier FROM './supplier.tbl' DELIMITER '|';
\Copy customer FROM './customer.tbl' DELIMITER '|';
\Copy lineitem FROM './lineitem.tbl' DELIMITER '|';
\Copy partsupp FROM './partsupp.tbl' DELIMITER '|';
\Copy orders FROM './orders.tbl' DELIMITER '|';


-- For table REGION
ALTER TABLE REGION
ADD PRIMARY KEY (R_REGIONKEY);

-- For table NATION
ALTER TABLE NATION
ADD PRIMARY KEY (N_NATIONKEY);

ALTER TABLE NATION
ADD FOREIGN KEY (N_REGIONKEY) references REGION;
CREATE INDEX nation_regionkey ON NATION(N_REGIONKEY);


-- For table PART
ALTER TABLE PART
ADD PRIMARY KEY (P_PARTKEY);



-- For table SUPPLIER
ALTER TABLE SUPPLIER
ADD PRIMARY KEY (S_SUPPKEY);

ALTER TABLE SUPPLIER
ADD FOREIGN KEY (S_NATIONKEY) references NATION;
CREATE INDEX supplier_nationkey ON SUPPLIER(S_NATIONKEY);


-- For table PARTSUPP
ALTER TABLE PARTSUPP
ADD PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);



-- For table CUSTOMER
ALTER TABLE CUSTOMER
ADD PRIMARY KEY (C_CUSTKEY);

ALTER TABLE CUSTOMER
ADD FOREIGN KEY (C_NATIONKEY) references NATION;
CREATE INDEX customer_nationkey on CUSTOMER(C_NATIONKEY);

-- For table LINEITEM
ALTER TABLE LINEITEM
ADD PRIMARY KEY (L_ORDERKEY,L_LINENUMBER);



-- For table ORDERS
ALTER TABLE ORDERS
ADD PRIMARY KEY (O_ORDERKEY);



-- For table PARTSUPP
ALTER TABLE PARTSUPP
ADD FOREIGN KEY (PS_SUPPKEY) references SUPPLIER;
CREATE INDEX partsupp_suppkey on PARTSUPP(PS_SUPPKEY);

ALTER TABLE PARTSUPP
ADD FOREIGN KEY (PS_PARTKEY) references PART;
CREATE INDEX partsupp_partkey on PARTSUPP(PS_PARTKEY);

-- For table ORDERS
ALTER TABLE ORDERS
ADD FOREIGN KEY (O_CUSTKEY) references CUSTOMER;
CREATE INDEX orders_custkey on ORDERS(O_CUSTKEY);

-- For table LINEITEM
ALTER TABLE LINEITEM
ADD FOREIGN KEY (L_ORDERKEY)  references ORDERS;
CREATE INDEX lineitem_orderkey on LINEITEM(L_ORDERKEY);


ALTER TABLE LINEITEM
ADD FOREIGN KEY (L_PARTKEY,L_SUPPKEY) references PARTSUPP;
CREATE INDEX lineitem_part_supp on LINEITEM(L_PARTKEY,L_SUPPKEY);
